name: epylabel2
channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - dash=2.11.1
  - fastparquet
  - geopandas=0.13.2
  - matplotlib=3.7.2
  - numpy=1.25.1
  - pandas=2.0.3
  - pre-commit
  - plotly=5.15.0
  - pyarrow=12.0.1
  - pytest=7.4.0
  - python=3.11.4
  - r=4.1
  - requests=2.31.0
  - rpy2=3.3
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn=0.13.2
  - shapely=2.0.1
  - sphinx=7.1.2
  - sphinxcontrib-applehelp=1.0.4
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml
  - tqdm=4.65.0
